name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.0.1

  # Firebase & Authentication
  google_sign_in: ^6.1.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.3.0

  cupertino_icons: ^1.0.8

  # Networking & Media
  http: ^1.6.0
  camera: ^0.10.5+6
  image_picker: ^1.2.1

dev_dependencies:
  cached_network_image: ^3.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Generador de íconos
  flutter_launcher_icons: ^0.14.4

# Configuración del generador de íconos
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/
    - assets/icon.png
